defaults:
  - model: cnn
  - loss: cross_entropy
  - optimizer: adam
  - scheduler: step_lr
  - augmentation: none
  - _self_

training:
  - epochs: 15
  - patience: 10
  - verbose: True

data:
  - batch_size: 64
  - data_dir: "./data"
  - debug-mode : True

wanb:
  - project: "cifar10-classifier"
  - run_name: "Training with W&B"